[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
decorations = "None"
opacity = 0.97
blur = true
dynamic_title = true

[colors]
primary.background = "#192129"
primary.foreground = "#c4dde8"
